/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/22/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CallerLocation 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5538119745263599627L;
    private String address;
    private String city;
    private String country;
    private String name;
    private int postalCode;
    private String region;
    private int unitNumber;
    private String unitType;
    /** GETTER
     * Address
     */
    @JsonGetter("address")
    public String getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * Address
     */
    @JsonSetter("address")
    public void setAddress (String value) { 
        this.address = value;
        notifyObservers(this.address);
    }
 
    /** GETTER
     * City
     */
    @JsonGetter("city")
    public String getCity ( ) { 
        return this.city;
    }
    
    /** SETTER
     * City
     */
    @JsonSetter("city")
    public void setCity (String value) { 
        this.city = value;
        notifyObservers(this.city);
    }
 
    /** GETTER
     * Country Name
     */
    @JsonGetter("country")
    public String getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * Country Name
     */
    @JsonSetter("country")
    public void setCountry (String value) { 
        this.country = value;
        notifyObservers(this.country);
    }
 
    /** GETTER
     * Location Name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Location Name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * Postal Code
     */
    @JsonGetter("postal_code")
    public int getPostalCode ( ) { 
        return this.postalCode;
    }
    
    /** SETTER
     * Postal Code
     */
    @JsonSetter("postal_code")
    public void setPostalCode (int value) { 
        this.postalCode = value;
        notifyObservers(this.postalCode);
    }
 
    /** GETTER
     * Region
     */
    @JsonGetter("region")
    public String getRegion ( ) { 
        return this.region;
    }
    
    /** SETTER
     * Region
     */
    @JsonSetter("region")
    public void setRegion (String value) { 
        this.region = value;
        notifyObservers(this.region);
    }
 
    /** GETTER
     * Unit Number
     */
    @JsonGetter("unit_number")
    public int getUnitNumber ( ) { 
        return this.unitNumber;
    }
    
    /** SETTER
     * Unit Number
     */
    @JsonSetter("unit_number")
    public void setUnitNumber (int value) { 
        this.unitNumber = value;
        notifyObservers(this.unitNumber);
    }
 
    /** GETTER
     * Unit Type
     */
    @JsonGetter("unit_type")
    public String getUnitType ( ) { 
        return this.unitType;
    }
    
    /** SETTER
     * Unit Type
     */
    @JsonSetter("unit_type")
    public void setUnitType (String value) { 
        this.unitType = value;
        notifyObservers(this.unitType);
    }
 
}
 