/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/22/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Routing 
        extends RoutingBase {
    private static final long serialVersionUID = 5139047300700159724L;
    private String sipUser;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sip_user")
    public String getSipUser ( ) { 
        return this.sipUser;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sip_user")
    public void setSipUser (String value) { 
        this.sipUser = value;
        notifyObservers(this.sipUser);
    }
 
}
 